language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "12"

sudo: false

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

cache:
  directories:
    - $HOME/.cache/yarn

script:
  - yarn
  - yarn run compile
  - yarn run test